#!/bin/bash
echo ========================export arm tools at current dir=======================================
echo =======================example arm..objdump addr2line etc ====================================
echo ======================-have to use . or source into include shell env ========================
. 8976_1_qcom
. build/envsetup.sh
lunch panda01a_msm8952_64-userdebug
cd -
echo =======================eheck result ====================================================
arm-linux-androideabi-objcopy --version
