# This file was generated by extconf.rb
module CommandT
  module Metadata
    EXPECTED_RUBY_VERSION = "1.9.3"
    EXPECTED_RUBY_PATCHLEVEL = 484
    UNKNOWN = false
  end # module Metadata
end # module CommandT
