#!/bin/bash
proj_dir=/media/zhl/second/2qcom/msm8939-la-2-1
echo ===============================================================
echo "Now into qcom build modem project just for 8939 spirit L proj!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo proj_dir = $proj_dir
echo ===============================================================
cd $proj_dir/modem_proc/build/ms
pwd
./build.sh 8936.gen.prod -c
./build.sh 8936.gen.prod -k
cd $proj_dir
#p ~/shell_my/unexeshell/contents8936_mirageplus01a_msm8916_64.xml contents.xml
git checkout contents.xml
cp contents_VG_8939_64.xml contents.xml
sed 's/msm8916_64/mobeeplus01a_msm8916_64/g' -i contents.xml
cd $proj_dir/common/build
python update_common_info.py
cd $proj_dir/common/build/bin
