#!/bin/bash
echo ===============================================================
#. sun_java
echo "Now into qcom a android project mobeeplus_imobile_customer"
echo ===============================================================
echo ===============================================================
cd /media/zhl/second/mobeeplus_imobile_customer_tmp/msm8939-la-2-1/LINUX/android
pwd
function print_usage(){
echo Usage!!
echo =================================================================
echo command ----------------:-----meaning
echo "add command at here"
echo =================================================================
echo =====================modem command ==============================
}
 print_usage
