#!/bin/bash
echo ===============================================================
#. sun_java
echo "Now into qcom a android project ==========mobeeplus reliance customer"
echo ===============================================================
cd /media/zhl/second/8939_1_l/msm8939-la-2-1/LINUX/android
pwd
function print_usage(){
echo Usage!!
echo =================================================================
echo command ----------------:-----meaning
echo "add command at here"
echo =================================================================
echo =====================modem command ==============================
}
 print_usage
