#!/bin/bash
echo ===============================================================
#. sun_java
echo "Now into qcom a android project =====8976 msm proj"
echo ===============================================================
echo ===============================================================
cd /media/zhl/second/8976_1_qcom/msm8976
pwd
function print_usage(){
echo Usage!!
echo =================================================================
echo command ----------------:-----meaning
echo "add command at here"
echo =================================================================
echo =====================modem command ==============================
}
 print_usage
