#!/bin/bash
echo ===============================================================
#. sun_java
echo "Now into qcom a android project =====8976 msm proj"
echo ===============================================================
echo ===============================================================
cd /home/zhl/mycode/8976_qcom_2/msm8976/LINUX/android
pwd
function print_usage(){
echo Usage!!
echo =================================================================
echo command ----------------:-----meaning
echo "add command at here"
echo =================================================================
echo =====================modem command ==============================
}
 print_usage
