#!/bin/bash
echo ===============================================================
#. sun_java
echo "Now into hicam android project !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo ===============================================================
echo "[into factory] : input text *#*#13646633#*#*                    "
echo "[pdf key]:       9621073404                                          "
echo "[touch i2c] :    /sys/devices/platform/mt-i2c.2/i2c-2/2-0015       "
echo "[touch force up]: elan_iap /system/etc/14f0_1103.ekt 0x15 2k   "
echo "[WLAN] iperf -c 192.168.1.100 -i 3 -t 120 –P 2 ; iperf -s -P 2"
echo "hicam it push command : git push origin hicam-baseline:refs/for/hicam-baseline"
echo ===============================================================
config=ckt95_lw_kk 
echo config = $config
echo build user version : ./mk -t -o=TARGET_BUILD_VARIANT=user $config n
cd /home/zhl/mycode/hicam/mt6595_kk 
pwd
function print_usage(){
echo Usage!!
echo =================================================================
echo command ----------------:-----meaning
echo $0 n_pre ------------:-----new build preloader
echo $0 r_pre ------------:-----build preloader just modify file
echo $0 n_kernel ---------:-----new build kernel
echo $0 r_kernel ---------:-----build kernl just modifify file
echo $0 n_bootimage ------:-----new build bootimage 
echo $0 r_bootimage ------:-----build bootimage just modify file
echo $0 n_recovery -------:-----new build recovery
echo $0 r_recovery -------:-----build recovery just modify file
echo $0 n_all ------------:-----new build all project
echo $0 r_all ------------:-----build all project just modify file
echo $0 n_lk -------------:-----new build lk
echo $0 r_lk -------------:-----build lk just modify file 
echo ==================================================================
}
if [ $# -eq 0 ]
then
 echo "just into $0 dir"
 print_usage

elif [ $1 == "n_pr" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config n pl

elif [ $1 == "n_all" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config n 

elif [ $1 == "n_bootimage" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config n bootimage

elif [ $1 == "n_kernel" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config n k

elif [ $1 == "n_lk" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config n lk

elif [ $1 == "n_recovery" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config n recoveryimage

elif [ $1 == "r_pr" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config r pl

elif [ $1 == "r_all" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config r

elif [ $1 == "r_bootimage" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config r bootimage

elif [ $1 == "r_kernel" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config r k

elif [ $1 == "r_recovery" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config r recoveryimage 

elif [ $1 == "r_lk" ]
then
 echo "just into $1  function"
 ./mk -t listp
 ./mk -t $config r lk

else 
 print_usage
 echo "Nothing DONE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
fi
