#!/bin/bash
function print_usage(){
#conflict with some command,eg find or sed,some print usage means cat other_shell_usage
cat ~/shell_my/unexeshell/other_shell_usage
}
if [ $# -eq 0 ]
then
	echo "just show usage"
	print_usage

elif [ $1 == "normal_proj_tags_update" ]
then
	echo "update normal proj cscope ctags current dir"
find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.cc' -o -name '*.java'  -o -name '*.sh' -o -name '*.mk' -o -name '*.prop' -o -name '*.xml' -o -name '*config*' -o -name 'Makefile' -o -name '*.rc' -o -name 'platform' -o -name 'Drivers' -o -name '*.dts' -o -name '*.dtsi' -o -name '*.scons' -o -name '*.api' -o -name '*.tla' -o -name '*.smh' -o -name '*.smi' -o -name '*.smt' -o -name '*.idl' -o -name '*.te' -o -name '*.py' -o -name '*.S' > cscope.files 
cscope -bkq -i cscope.files 

elif [ $1 == "mtk_kk_old_kernel_tags_update" ]
then
 echo "update mtk kk old android kernel proj cscope tags"
 find  mediatek/ kernel/ -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.cc' -o -name '*.java'  -o -name '*.sh' -o -name '*.mk' -o -name '*.prop' -o -name '*.xml' -o -name '*config*' -o -name 'Makefile' -o -name '*.rc' -o -name 'platform' -o -name 'Drivers' -o -name '*.dts' -o -name '*.dtsi' -o -name '*.te' -o -name '*.py' -o -name '*.S' > cscope.files 
 cscope -bkq -i cscope.files 

elif [ $1 == "kernel_arm32_cscope" ]
then
	echo "gen cscope tags for ARCH=arm kernel: make cscope ARCH=arm"
	make cscope ARCH=arm
	echo "done........................................."

elif [ $1 == "kernel_arm64_cscope" ]
then
	echo "gen cscope tags for ARCH=arm64 kernel: make cscope ARCH=arm64"
	make cscope ARCH=arm64
	echo "done........................................."
else 
 print_usage
 echo "Nothing DONE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
fi
