#!/bin/bash
echo ===============================================================
function print_usage(){
echo Usage!!
echo =================================================================
echo "evince xxx.pdf"
echo ==================================================================
}
if [ $# -eq 0 ]
then
 print_usage

else
 echo "open PDF: $1"
 evince "$1"
fi
