#!/bin/bash
echo "find " $1 "from pdf"
find . -name "*.pdf" | while read pdf
do
echo "========================================================================================="
echo $pdf
	pdftotext "$pdf"
done

