#!/bin/sh
#osd_fake_translucent_bg : on off
#animations : on off
#osd_fake_translucent_bg : on off
#osd_vposition : top bottom center
#osd_halignmen : left right
for i in `seq 80`
do
gnome-osd-client -f "<message id='rest' osd_fake_translucent_bg='on' osd_vposition='center' animations='on' hide_timeout='2000' osd_halignment='center' >休息一下</message>"
echo $i
sleep 3
done
