#!/bin/bash
echo ===================================================================================
adb wait-for-device
echo ===find adb devices=====
adb devices
sleep 1
echo =========try to root now===========================================================
adb shell setprop ro.debuggable 1
echo =========plug out usb and then plugn in===========================================
adb root
echo =========plug out usb and then plugn in===========================================
exit


