cc_library(
    name = "find_rw_dir",
    hdrs = [
        "find_rw_dir.h",
    ],
    srcs = ["find_rw_dir.cpp", ],
    includes = ["."],
    visibility=["//visibility:public"],
)

cc_binary (
    name = "find_rw_dir_bin",
    hdrs = [
        "find_rw_dir.h",
    ],
    srcs = ["find_rw_dir.cpp", ],
)
